# Generated by Django 4.2 on 2025-01-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.TextField(blank=True, max_length=256, null=True)),
                ('priority_level', models.IntegerField(default=1)),
                ('is_starred', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tasks.categories')),
            ],
        ),
    ]
