# Generated by Django 4.2 on 2025-01-11 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_task', models.CharField(max_length=16)),
            ],
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='category',
            new_name='name',
        ),
        migrations.AddField(
            model_name='task',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.categories'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority_level',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='type_of_task',
            field=models.OneToOneField(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.tasktype'),
        ),
    ]
