# Generated by Django 4.2 on 2025-01-14 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_priority_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type_of_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.typeoftask'),
        ),
    ]
