# Generated by Django 4.2 on 2025-01-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_category_options_task_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progression_end',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='progression_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='todo_status',
            field=models.IntegerField(choices=[('Incomplete', 1), ('Work In Progress', 2), ('Done', 3)], default=1),
        ),
    ]
