# Generated by Django 4.2 on 2025-01-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_category_of_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='todo_status',
            field=models.IntegerField(choices=[('1 → Incomplete', 1), (' 2 → Work In Progress', 2), ('3 → Done', 3)], default=1),
        ),
    ]
