# Generated by Django 4.2 on 2025-01-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_task_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='todo_status',
            field=models.IntegerField(choices=[(1, '1 → Incomplete'), (2, '2 → Work In Progress'), (3, '3 → Done')], default=1),
        ),
    ]
